# Pseudo image creating script
# using a syntax similar to Dockerfile

FROM JS-API-Featured-CentOS7-May-20-2019

RUN yum install https://repo.opensciencegrid.org/osg/3.5/osg-3.5-el7-release-latest.rpm
RUN yum install epel-release yum-plugin-priorities
RUN yum install condor
RUN yum update


ADD 98_security.config /etc/condor/config.d/98_security.config 
ADD 99_daemons.config /etc/condor/config.d/99_daemons.config

# Needs to be the same across the pool
# condor_store_cred -f <filename>
ADD pool_password /etc/condor/pool_password

# We are assuming a specific IP and DNS name, update as needed
RUN echo "osg-ce-collector.osg.cybera-cloud.org" > /etc/hostname

RUN echo "10.2.4.22 osg-ce-collector.osg.cybera-cloud.org osg-ce-collector" >> /etc/hosts
RUN echo "10.2.4.40 249cc.yeg.cybera.ca 249cc" >> /etc/hosts

RUN systemctl enable condor
RUN systemctl start condor

